version: '3'

services:
  
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        UID: ${HOST_UID}
        GID: ${HOST_GID}
    volumes:
      - ./:/var/www/html
    ports:
      - "${WEB_PORT}:80"
    networks:
      - app_network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    depends_on:
      - db
  

  db:
    
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    
    ports:
      - "${DB_PORT}:3306"
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
    driver: local
